M48
; DRILL file {KiCad 7.0.2} date Thu May 18 15:41:47 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-18T15:41:47-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.1845Y-2.6394
X5.3755Y-2.6394
T2
X5.1727Y-2.5201
X5.3873Y-2.5201
T0
M30
