name: 'Doxygen'

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: lib/docs/html
          config_file: Doxyfile
