name: 'Doxygen'

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

defaults:
  run:
    working-directory: lib

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set version
        run: echo "PROJECT_NUMBER = `git describe --tags`" >> Doxyfile
      - name: Generate Documentation
        uses: mattnotmitt/doxygen-action@edge
        with:
          working-directory: 'lib/'
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          name: ${{  }}
          dir: lib/docs/html
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}